Create pop windows
peteryeungtt/My-Portfolio pull request #15
Opened 2023-05-18 17:03 UTC by peteryeungtt

In this project we needed to implement a popup window that includes the project details in both desktop and mobile in the project section.

2023-05-18 19:05 UTC, ridwanediallo requested changes
# Changes Required ♻️
## Hi @peteryeungtt , 
![AlmostThereReachGIF](https://user-images.githubusercontent.com/55918904/191301799-36d07166-0e35-4582-a231-7a2d780f7783.gif)

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## (Highlights) Good Points: :+1:
- You documented your work professionally. ✔
- You used GitHub flow correctly. ✔
- Your PR has a good title. ✔


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-18 19:05 UTC, ridwanediallo commented on index.js
> +}
- [ ] Hello there, @peteryeungtt. Congratulations on submitting your project for review. However, for some reason, the entire work section is not displaying, making it impossible to determine whether the popup modal is functioning properly. Please fix that problem and ensure that all of the project's requirements are met. :ok_hand: 😊

### Work section not displaying :point_down: 

![Screenshot from 2023-05-18 18-48-48](https://github.com/peteryeungtt/My-Portfolio/assets/89228743/77987911-276f-4d18-b330-046fde2849a1)

2023-05-18 19:14 UTC, peteryeungtt commented on index.js
> +}
@ridwanediallo That is weird it is working on my end

2023-05-18 19:21 UTC, peteryeungtt commented on index.js
> +}
@ridwanediallo 
![image](https://github.com/peteryeungtt/My-Portfolio/assets/66895564/b89dde9d-fecc-42b0-8603-157b05c3904f)

2023-05-18 19:21 UTC, peteryeungtt commented on index.js
> +}
![image](https://github.com/peteryeungtt/My-Portfolio/assets/66895564/64c4a63d-933e-45ac-adb7-1f9e4cb5ca79)

2023-05-18 19:22 UTC, peteryeungtt commented on index.js
> +}
@ridwanediallo I just clone my repo n checkout to branch "created_popups"
It is working fine on my end, I do not understand

2023-05-18 19:25 UTC, peteryeungtt commented on index.js
> +}
@ridwanediallo I dont know what to do or troubleshoot because it is working on my end, I even tried to clone it 3 times

2023-05-18 20:04 UTC, peteryeungtt commented on index.js
> +}
@ridwanediallo please check my live link:  https://peteryeungtt.github.io/My-Portfolio/
It is working properly.

2023-05-18 20:14 UTC, Qoosim requested changes
#  *Status: Required Changes* :recycle: 

Hi @team, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


## Highlights
-  No linter errors. :heavy_check_mark: 
-  Good README file. :heavy_check_mark: 
-  Correct GitHub Flow. :heavy_check_mark: 

![](https://camo.githubusercontent.com/38ce8c8b213b08e2d9bb85a0b79702ad512f3910f803ec3d7917b4e0110c9044/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7741366159414f336a4836526d55494259732f67697068792e676966)

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-18 20:14 UTC, Qoosim commented on styles.css
> +
- [ ] It is required to produce a close replica of the figma design. Kindly check how your design displays on the mobile with how it should be on the figma. Some content of your modal on mobile are not properly visible. Kindly adjust your styling to make them visible as we have them on the Figma design.

### Your Design

![your-mobile-popup](https://github.com/peteryeungtt/My-Portfolio/assets/26597432/2f789792-8b57-4864-bd63-998bd6c2d2ce)

### Figma Design
![temp-mobilepopup](https://github.com/peteryeungtt/My-Portfolio/assets/26597432/523a1fe1-4d50-47ba-906e-190566ee939f)

2023-05-19 00:09 UTC, V-Blaze approved these changes
Hi @peteryeungtt  , 

# Approved 🟢 🟢 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![giphy](https://user-images.githubusercontent.com/107632780/229644741-7dea3027-bf3f-4416-855b-46095e3bf6d5.gif)

## Highlights

- Meaningful commit messages💯
-  Project works as expected👍
-  Design looks like the Fgima design 🟢 👍

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-19 00:11 UTC, merged

2023-05-19 12:36 UTC, ridwanediallo commented on index.js
> +}
- [ ] Hello there, @peteryeungtt. I apologize for all of the comments; I was away. I'm not sure what the problem was. When I run the project exactly as I received it yesterday, I get the same result. :point_down: 
![Screenshot from 2023-05-19 12-27-43](https://github.com/peteryeungtt/My-Portfolio/assets/89228743/3d76f6e4-e0b4-41cd-bbf5-f4a9ed5d0f5a)

What browser do you use?